from django.db import models
from PIL import Image
import datetime

# Create your models here.

class Record(models.Model):
    player_id = models.AutoField
    player_name = models.CharField(max_length=50)
    player_category = (
        ("Batsman", "batsman"),
        ("Bowler", "bowler"),
        ("All-Rounder", "all-rounder"),
        ("Wicket-keeper", "wicket-keeper"),
    )
    category = models.CharField(max_length=15,
                                choices=player_category,
                                default="All-Rounder")
    player_batting_style = models.CharField(max_length=50, default="")
    player_bowling_style = models.CharField(max_length=50, default="")
    player_batting_no = models.CharField(max_length=50, default="")
    player_age = models.IntegerField(default=0)
    player_rank = models.CharField(max_length=50, default="")
    player_desc = models.CharField(max_length=500, default="")
    image = models.FileField(upload_to='club/images', default="")


    def __str__(self):
        return self.player_name


class Photo(models.Model):
    title = models.CharField(max_length=200)
    image = models.FileField(upload_to='club/images', null=True , blank=True)

    def __unicode__(self):
        return self.title

class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=70, default="")
    phone = models.CharField(max_length=70, default="")
    desc = models.CharField(max_length=500, default="")


    def __str__(self):
        return self.name


class Nxt_Match(models.Model):
    match_status = (
        ("Won", "won"),
        ("Lost", "lost"),
        ("Draw", "draw"),
    )
    match_result = models.CharField(max_length=5,
                                choices=match_status,
                                default="Won")
    Winner = models.CharField(max_length=200, default=" Match Drawn")
    sc_link = models.CharField(max_length=100, default="no Video Available")
    match_date = models.DateTimeField(auto_now_add=False)
    n_match_team1 = models.CharField(max_length=100, default="Friends GymKhana C C")
    n_match_team2 = models.CharField(max_length=100, default="")
    n_match_location = models.CharField(max_length=200, default="")
    Team1_Batsman_Name1 = models.CharField(max_length=70, default="")
    Team1_Batsman_Name2 = models.CharField(max_length=70, default="")
    Team1_Batsman_Name3 = models.CharField(max_length=70, default="")
    Team1_Batsman_Name4 = models.CharField(max_length=70, default="")
    Team1_Batsman_Name5 = models.CharField(max_length=70, default="")
    Team1_Batsman_Name6 = models.CharField(max_length=70, default="")
    Team1_Batsman_Name7 = models.CharField(max_length=70, default="")
    Team1_Batsman_Name8 = models.CharField(max_length=70, default="")
    Team1_Batsman_Name9 = models.CharField(max_length=70, default="")
    Team1_Batsman_Name10 = models.CharField(max_length=70, default="")
    Team1_Batsman_Name11 = models.CharField(max_length=70, default="")
    Team1_Batsman_Runs1 = models.IntegerField(default="not yet bat")
    Team1_Batsman_Runs2 = models.IntegerField(default="not yet bat")
    Team1_Batsman_Runs3 = models.IntegerField(default="not yet bat")
    Team1_Batsman_Runs4 = models.IntegerField(default="not yet bat")
    Team1_Batsman_Runs5 = models.IntegerField(default="not yet bat")
    Team1_Batsman_Runs6 = models.IntegerField(default="not yet bat")
    Team1_Batsman_Runs7 = models.IntegerField(default="not yet bat")
    Team1_Batsman_Runs8 = models.IntegerField(default="not yet bat")
    Team1_Batsman_Runs9 = models.IntegerField(default="not yet bat")
    Team1_Batsman_Runs10 = models.IntegerField(default="not yet bat")
    Team1_Batsman_Runs11 = models.IntegerField(default="not yet bat")
    Balls1 = models.IntegerField(default="0")
    Balls2 = models.IntegerField(default="0")
    Balls3 = models.IntegerField(default="0")
    Balls4 = models.IntegerField(default="0")
    Balls5 = models.IntegerField(default="0")
    Balls6 = models.IntegerField(default="0")
    Balls7 = models.IntegerField(default="0")
    Balls8 = models.IntegerField(default="0")
    Balls9 = models.IntegerField(default="0")
    Balls10 = models.IntegerField(default="0")
    Balls11 = models.IntegerField(default="0")
    Four1 = models.IntegerField(default="0")
    Four2 = models.IntegerField(default="0")
    Four3 = models.IntegerField(default="0")
    Four4 = models.IntegerField(default="0")
    Four5 = models.IntegerField(default="0")
    Four6 = models.IntegerField(default="0")
    Four7 = models.IntegerField(default="0")
    Four8 = models.IntegerField(default="0")
    Four9 = models.IntegerField(default="0")
    Four10 = models.IntegerField(default="0")
    Four11 = models.IntegerField(default="0")
    Six1 = models.IntegerField(default="0")
    Six2 = models.IntegerField(default="0")
    Six3 = models.IntegerField(default="0")
    Six4 = models.IntegerField(default="0")
    Six5 = models.IntegerField(default="0")
    Six6 = models.IntegerField(default="0")
    Six7 = models.IntegerField(default="0")
    Six8 = models.IntegerField(default="0")
    Six9 = models.IntegerField(default="0")
    Six10 = models.IntegerField(default="0")
    Six11 = models.IntegerField(default="0")
    Team2_Bowler_Name1 = models.CharField(max_length=70, default="Did Not Bowl")
    Team2_Bowler_Name2 = models.CharField(max_length=70, default="Did Not Bowl")
    Team2_Bowler_Name3 = models.CharField(max_length=70,default="Did Not Bowl")
    Team2_Bowler_Name4 = models.CharField(max_length=70, default="Did Not Bowl")
    Team2_Bowler_Name5 = models.CharField(max_length=70, default="Did Not Bowl")
    Team2_Bowler_Name6 = models.CharField(max_length=70, default="Did Not Bowl")
    Team2_Bowler_Name7 = models.CharField(max_length=70, default="Did Not Bowl")
    Team2_Bowler_Name8 = models.CharField(max_length=70, default="Did Not Bowl")
    Team2_Bowler_Name9 = models.CharField(max_length=70, default="Did Not Bowl")
    Team2_Bowler_Name10 = models.CharField(max_length=70, default="Did Not Bowl")
    Team2_Bowler_Name11 = models.CharField(max_length=70, default="Did Not Bowl")
    Team2_Bowler_Runs1 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Runs2 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Runs3 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Runs4 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Runs5 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Runs6 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Runs7 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Runs8 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Runs9 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Runs10 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Runs11 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets1 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets2 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets3 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets4 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets5 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets6 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets7 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets8 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets9 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets10 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Wickets11 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs1 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs2 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs3 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs4 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs5 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs6 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs7 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs8 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs10 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Overs11 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours1 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours2 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours3 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours4 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours5 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours6 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours7 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours8 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours9 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours10 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Fours11 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six1 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six2 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six3 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six4 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six5 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six6 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six7 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six8 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six9 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six10 = models.CharField(max_length=70, default="0")
    Team2_Bowler_Six11 = models.CharField(max_length=70, default="0")
    Team2_Batsman_Name1 = models.CharField(max_length=70, default="no yet bat")
    Team2_Batsman_Name2 = models.CharField(max_length=70, default="not yet bat")
    Team2_Batsman_Name3 = models.CharField(max_length=70, default="not yet bat")
    Team2_Batsman_Name4 = models.CharField(max_length=70, default="not yet bat")
    Team2_Batsman_Name5 = models.CharField(max_length=70, default="not yet bat")
    Team2_Batsman_Name6 = models.CharField(max_length=70, default="not yet bat")
    Team2_Batsman_Name7 = models.CharField(max_length=70, default="not yet bat")
    Team2_Batsman_Name8 = models.CharField(max_length=70, default="not yet bat")
    Team2_Batsman_Name9 = models.CharField(max_length=70, default="not yet bat")
    Team2_Batsman_Name10 = models.CharField(max_length=70, default="not yet bat")
    Team2_Batsman_Name11 = models.CharField(max_length=70, default="not yet bat")
    Team2_Batsman_Runs1 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Runs2 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Runs3 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Runs4 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Runs5 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Runs6 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Runs7 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Runs8 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Runs9 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Runs10 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Runs11 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls1 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls2 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls3 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls4 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls5 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls6 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls7 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls8 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls9 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls10 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Balls11 = models.IntegerField(default="not yet bat")
    Team2_Batsman_Four1 = models.IntegerField(default="0")
    Team2_Batsman_Four2 = models.IntegerField(default="0")
    Team2_Batsman_Four3 = models.IntegerField(default="0")
    Team2_Batsman_Four4 = models.IntegerField(default="0")
    Team2_Batsman_Four5 = models.IntegerField(default="0")
    Team2_Batsman_Four6 = models.IntegerField(default="0")
    Team2_Batsman_Four7 = models.IntegerField(default="0")
    Team2_Batsman_Four8 = models.IntegerField(default="0")
    Team2_Batsman_Four9 = models.IntegerField(default="0")
    Team2_Batsman_Four10 = models.IntegerField(default="0")
    Team2_Batsman_Four11 = models.IntegerField(default="0")
    Team2_Batsman_Six1 = models.IntegerField(default="0")
    Team2_Batsman_Six2 = models.IntegerField(default="0")
    Team2_Batsman_Six3 = models.IntegerField(default="0")
    Team2_Batsman_Six4 = models.IntegerField(default="0")
    Team2_Batsman_Six5 = models.IntegerField(default="0")
    Team2_Batsman_Six6 = models.IntegerField(default="0")
    Team2_Batsman_Six7 = models.IntegerField(default="0")
    Team2_Batsman_Six8 = models.IntegerField(default="0")
    Team2_Batsman_Six9 = models.IntegerField(default="0")
    Team2_Batsman_Six10 = models.IntegerField(default="0")
    Team2_Batsman_Six11 = models.IntegerField(default="0")
    Team1_Bowler_Name1 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Name2 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Name3 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Name4 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Name5 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Name6 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Name7 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Name8 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Name9 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Name10 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Name11 = models.CharField(max_length=70, default="Did not bowl")
    Team1_Bowler_Runs1 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Runs2 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Runs3 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Runs4 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Runs5 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Runs6 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Runs7 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Runs8 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Runs9 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Runs10 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Runs11 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets1 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets2 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets3 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets4 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets5 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets6 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets7 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets8 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets9 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets10 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Wickets11 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs1 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs2 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs3 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs4 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs5 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs6 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs7 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs8 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs10 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Overs11 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours1 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours2 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours3 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours4 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours5 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours6 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours7 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours8 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours9 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours10 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Fours11 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six1 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six2 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six3 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six4 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six5 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six6 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six7 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six8 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six9 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six10 = models.CharField(max_length=70, default="0")
    Team1_Bowler_Six11 = models.CharField(max_length=70, default="0")


class New(models.Model):
    news_date = models.DateTimeField(auto_now_add=False)
    news_short_detail = models.CharField(max_length=70, default="")
    news_long_detail = models.CharField(max_length=500, default="")
    news_image = models.FileField(upload_to='shop/images', default="")
    link = models.CharField(max_length=100 , default="")


class Videos(models.Model):
    v_image = models.ImageField(upload_to='shop/images', default="")
    v_link = models.CharField(max_length=100)

class UpComingMatches(models.Model):
    team1 = models.CharField(max_length=100 ,default="Friends GymKhana C C")
    team2 = models.CharField(max_length=100)
    time = models.DateTimeField(auto_now_add=False)
    ground = models.CharField(max_length=100)